# based on https://homeassistant.com.de/homeassistant/modbus-einbindung-lambda-in-home-assistant/

#### Lambda WP:
- platform: template
  sensors:
    eu13l_ambient_operating_state_txt:
      friendly_name: "EU13L_Ambient_Operating_State_txt"
      value_template: >
        {{ ['Off', 'Automatik', 'Manual', 'Error'][states('sensor.eu13l_ambient_operating_state')|int] }}
    eu13l_emgr_operating_state_txt:
      friendly_name: "EU13L_EMgr_Operating_State_txt"
      value_template: >
        {{ ['Off', 'Automatik', 'Manual', 'Error', 'Offline'][states('sensor.eu13l_emgr_operating_state')|int] }}
    eu13l_hp1_error_state_txt:
      friendly_name: "EU13L_Hp1_Error_State_txt"
      value_template: >
        {{ ['OK', 'Message', 'Warning', 'Alarm', 'Fault'][states('sensor.eu13l_hp1_error_state')|int] }}
    eu13l_hp1_state_txt:
      friendly_name: "EU13L_Hp1_State_txt"
      value_template: >
        {{ ['Init', 'Reference', 'Restart-Block', 'Ready', 'Start Pumps', 'Start Compressor', 'Pre-Regulation', 'Regulation', 'Not Used', 'Cooling', 'Defrosting', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Stopping', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Fault-Lock', 'Alarm-Block', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Not Used', 'Error-Reset'][states('sensor.eu13l_hp1_state')|int] }}
    #translated to german:
    eu13l_hp1_operating_state_txt:
      friendly_name: "EU13L_Hp1_Operating_State_txt"
      value_template: >
        {{ ['Standby', 'Heizung', 'WW-Bereitung', 'Cold Climate', 'Zirkulieren', 'Defrost', 'Off', 'Frost', 'Standby-Frost', 'Not used', 'Sommer', 'Ferienbetrieb', 'Error', 'Warning', 'Info-Message', 'Time-Block', 'Release-Block', 'Mintemp-Block', 'Firmware-Download'][states('sensor.eu13l_hp1_operating_state')|int] }}
    #comment out if english version is preferred:
    # eu13l_hp1_operating_state_txt:
      # friendly_name: "EU13L_Hp1_Operating_State_txt"
      # value_template: >
        # {{ ['Standby', 'Central Heating', 'Domestic Hot Water', 'Cold Climate', 'Circulate', 'Defrost', 'Off', 'Frost', 'Standby-Frost', 'Not used', 'Summer', 'Holiday', 'Error', 'Warning', 'Info-Message', 'Time-Block', 'Release-Block', 'Mintemp-Block', 'Firmware-Download'][states('sensor.eu13l_hp1_operating_state')|int] }}
    eu13l_hp1_request_type_txt:
      friendly_name: "EU13L_Hp1_Request_Type_txt"
      value_template: >
        {{ ['No Request', 'Flow Pump Circulation', 'Central Heating', 'Central Cooling', 'Domestic Hot Water'][states('sensor.eu13l_hp1_request_type')|int] }}
    eu13l_boil1_operating_state_txt:
      friendly_name: "EU13L_Boil1_Operating_State_txt"
      value_template: >
        {{ ['Standby', 'Domestic Hot Water', 'Legio', 'Summer', 'Frost', 'Holiday', 'Prio-Stop', 'Error', 'Off', 'Prompt-DHW', 'Trailing-Stop', 'Temp-Lock', 'Standby-Frost'][states('sensor.eu13l_boil1_operating_state')|int] }}
    eu13l_buff1_operating_state_txt:
      friendly_name: "EU13L_Buff1_Operating_State_txt"
      value_template: >
        {{ ['Standby', 'Heating', 'Cooling', 'Summer', 'Frost', 'Holiday', 'Prio-Stop', 'Error', 'Off', 'Standby-Frost'][states('sensor.eu13l_buff1_operating_state')|int] }}
    eu13l_sol1_operating_state_txt:
      friendly_name: "EU13L_Sol1_Operating_State_txt"
      value_template: >
        {{ ['Standby', 'Heating', 'Error', 'Off'][states('sensor.eu13l_sol1_operating_state')|int] }}
    eu13l_hc1_operating_state_txt:
      friendly_name: "EU13L_Hc1_Operating_State_txt"
      value_template: >
        {{ ['Heating', 'Eco', 'Cooling', 'Floor-dry', 'Frost', 'Max-Temp', 'Error', 'Service', 'Holiday', 'Central Heating Summer', 'Central Cooling Winter', 'Prio-Stop', 'Off', 'Release-Off', 'Time-Off', 'Standby', 'Standby-Heating', 'Standby-Eco', 'Standby-Cooling', 'Standby-Frost', 'Standby-Floor-dry'][states('sensor.eu13l_hc1_operating_state')|int] }}
    eu13l_hc1_operating_mode_txt:
      friendly_name: "EU13L_Hc1_Operating_Mode_txt"
      value_template: >
        {{ ['Off', 'Manual', 'Automatik', 'Auto-Heating', 'Auto-Cooling', 'Frost', 'Summer', 'Floor-dry'][states('sensor.eu13l_hc1_operating_mode')|int] }}
    eu13l_hc2_operating_state_txt:
      friendly_name: "EU13L_Hc2_Operating_State_txt"
      value_template: >
        {{ ['Heating', 'Eco', 'Cooling', 'Floor-dry', 'Frost', 'Max-Temp', 'Error', 'Service', 'Holiday', 'Central Heating Summer', 'Central Cooling Winter', 'Prio-Stop', 'Off', 'Release-Off', 'Time-Off', 'Standby', 'Standby-Heating', 'Standby-Eco', 'Standby-Cooling', 'Standby-Frost', 'Standby-Floor-dry'][states('sensor.eu13l_hc2_operating_state')|int] }}
    eu13l_hc2_operating_mode_txt:
      friendly_name: "EU13L_Hc2_Operating_Mode_txt"
      value_template: >
        {{ ['Off', 'Manual', 'Automatik', 'Auto-Heating', 'Auto-Cooling', 'Frost', 'Summer', 'Floor-dry'][states('sensor.eu13l_hc2_operating_mode')|int] }}
    eu13l_hc3_operating_state_txt:
      friendly_name: "EU13L_Hc3_Operating_State_txt"
      value_template: >
        {{ ['Heating', 'Eco', 'Cooling', 'Floor-dry', 'Frost', 'Max-Temp', 'Error', 'Service', 'Holiday', 'Central Heating Summer', 'Central Cooling Winter', 'Prio-Stop', 'Off', 'Release-Off', 'Time-Off', 'Standby', 'Standby-Heating', 'Standby-Eco', 'Standby-Cooling', 'Standby-Frost', 'Standby-Floor-dry'][states('sensor.eu13l_hc3_operating_state')|int] }}
    eu13l_hc3_operating_mode_txt:
      friendly_name: "EU13L_Hc3_Operating_Mode_txt"
      value_template: >
        {{ ['Off', 'Manual', 'Automatik', 'Auto-Heating', 'Auto-Cooling', 'Frost', 'Summer', 'Floor-dry'][states('sensor.eu13l_hc3_operating_mode')|int] }}
